### ISSUE TITLE
IndexError during customization

### ISSUE THREAD

**Issue by Alastairsc** [Alastairm/django_env#37] opened 2015-10-15 00:54 UTC
tuple index out of range when trying to customise test B errors.csv. 

Exception Location:	/home/djangouser/django_env/mysite/errors/forms.py in dataString, line 31

**Comment by lilfolr** [comment] 2015-10-15 00:55
Duplicate of #35

**Comment by Alastairm** [comment] 2015-10-15 02:22
fixed, will pull the changes to the site

**Closed by Alastairm** 2015-10-15 02:22 UTC
