### ISSUE TITLE
Error when loading Cell errors tab

### ISSUE THREAD

**Issue by lilfolr** [Alastairm/django_env#35] opened 2015-10-14 15:09 UTC
Using file emails.csv
Error:
![image](https://cloud.githubusercontent.com/assets/9531064/10487828/79c5e6da-72c8-11e5-8c5d-2e411e2683a5.png)

**Comment by Alastairm** [comment] 2015-10-14 17:04
duplicate of issue #34

**Comment by Alastairm** [comment] 2015-10-14 17:04
duplicate of issue #34

**Closed by Alastairm** 2015-10-14 17:04 UTC
